backend:
  name: git-gateway
  branch: master # Branch to update (master by default)

media_folder: "images" # Media files will be stored in the repo under images
public_folder: "/images" # The src attribute for uploaded media will begin with /images

collections: # A list of collections the CMS should be able to edit  
  - name: "page"
    label: "Page"
    folder: "pages"
    create: true
    slug: "{{permalink}}"
    fields:
      - {label: "Layout", name: "layout", widget: "select", options: ["about", "blog", "contact", "gallery", "page"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string", default: "//"}
      - {label: "Body", name: "body", widget: "markdown", required: false}

  - name: "data"
    label: "Data"
    files: 
      - name: "featured_package"
        label: "Featured Package"
        file: "_data/featured_package.yml"
        fields: 
          - {label: "name", name: "Name", widget: "string"}
          - {label: "description", name: "Description", widget: "markdown"}
          - {label: "hex", name: "Hex.pm URL", widget: "string"}
          - {label: "github", name: "GitHub.com URL", widget: "string"}

      - name: "past_packages"
        label: "Past packages"
        file: "_data/past_packages.yml"
        fields:
          - {label: "name", name: "Name", widget: "string"}
          - {label: "description", name: "Description", widget: "markdown"}
          - {label: "hex", name: "Hex.pm URL", widget: "string"}
          - {label: "github", name: "GitHub.com URL", widget: "string"}
