backend:
  name: git-gateway
  branch: master # Branch to update (master by default)

media_folder: "images" # Media files will be stored in the repo under images
public_folder: "/images" # The src attribute for uploaded media will begin with /images

collections: # A list of collections the CMS should be able to edit  
  - label: "Page"
    name: "page"
    folder: "pages"
    create: true
    slug: "{{permalink}}"
    fields:
      - {label: "Layout", name: "layout", widget: "select", options: ["page"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string", default: "//"}
      - {label: "Body", name: "body", widget: "markdown", required: false}

  - label: "Package"
    name: "package"
    folder: "_packages"
    create: true
    slug: "{{permalink}}"
    fields:
      - {label: "Layout", name: "layout", widget: "select", options: ["page"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured", name: "featured", widget: "boolean"}
      - {label: "Permalink", name: "permalink", widget: "string", default: "//"}
      - {label: "Hex", name: "hex", widget: "string"}
      - {label: "Github", name: "github", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
